---
- name: Get current Objects Enablement Status
  uri:
    url: "https://{{ nutanix_host }}:{{ nutanix_port }}/api/nutanix/v3/services/oss/status"
    method: GET
    validate_certs: "{{ validate_certs }}"
    body_format: json
    status_code: 200
    headers:
      Authorization: "{{ nutanix_api_auth }}"
  register: nutanix_objects_current_state

- name: Debug nutanix_objects_current_state
  debug:
    var: nutanix_objects_current_state
  when:
    - nutanix_debug

- name: Current status of Nutanix Objects service(s)
  debug:
    msg: "Nutanix Objects is currently in a '{{ nutanix_objects_current_state.json.service_enablement_status }}' state."
