---
# tasks file for nutanix_role_prism_calm
- import_tasks: setup_api.yml

- name: "Task can only be run against Prism Central"
  ansible.builtin.fail:
    msg: "'nutanix_host' needs to be set to the IP or VIP of Prism Central. Please check the variable and try again."
  when:
    - nutanix_endpoint_prism_type != 'pc'

- name: Get Objects state
  include_tasks: get_state.yml

# - name: Check Objects Pre-Reqs
#   include_tasks: check_prereqs.yml
#   when:
#     - nutanix_objects_current_state.json.service_enablement_status != "ENABLED"
#     - nutanix_objects_enable | default(False)

- name: Enable Objects
  include_tasks: enable_feature.yml
  when:
    - nutanix_objects_current_state.json.service_enablement_status != "ENABLED"
    - nutanix_objects_enable | default(False)

- name: Disable Objects
  include_tasks: disable_feature.yml
  when:
    - nutanix_objects_current_state.json.service_enablement_status == "ENABLED"
    - nutanix_objects_enable | default(True)
